### ISSUE TITLE
quickstart.txt

### ISSUE THREAD

**Issue by Arno-Enslin** [googlei18n/sfntly#51]
quickstart.txt? WTF? Rename it to Quickstart_for_Java_or_C_or_whatever_developers_only.txt or write a new one, please.

Sorry, but I really don't understand this. You invest much time in developing tool packages like this, but you obviously hate users, that aren't developers. Or you simply don't know, that those users exist.

**Comment by behdad** [comment]
> Sorry, but I really don't understand this.

No worries.  That's mutual.  I don't understand what you mean by all your reports (here, AFDKO, fonttools) either :).

**Comment by Arno-Enslin** [comment]
> I don't understand what you mean by all your reports (here, AFDKO, fonttools) either :).
For whom do you develop tools like sfntly? For other programmers only? For programmers the quickstart guide is useless, because they know, what they have to do. For pure users it is useless, because they still don't know, what they have to do / what they have to install first. If you invest 100 hours in programming and one minute in the user guide only, you are routine-blinded.

**Comment by behdad** [comment]
This particular library is, for the most part, for developers.

Even if it was for end users, the building part does not need to be optimized for ordinary users.  You might try to get precompiled binaries from different sources (Linux distributions, MacPort, HomeBrew, etc, though I don't know any for Windows.)

Sorry, I'm not trying to be mean or hostile.  There's just too many different things to explain, if you don't know how to follow "build with ant".

**Comment by Arno-Enslin** [comment]
> There's just too many different things to explain, if you don't know how to follow "build with ant".

I doubt that. If you make the start a bit easier for ordinary end users (whoever these are), you will have more persons, that test the software and report the bugs, that they find.

**Comment by behdad** [comment]
No point continuing this discussion.

**Comment by Arno-Enslin** [comment]
[I could not resist.](https://github.com/adobe-type-tools/afdko/issues/113)
