### ISSUE TITLE
Chrome & Android Browser "OTS parsing error"

### ISSUE THREAD

**Issue by inbreaks** [googlei18n/sfntly#52]
Some ttf file parsing errors after sfntly processed into browsers will happen.

```
java -jar sfntly.jar -s "abc" foo.ttf new.ttf
```

Chrome & Android Browser use new.ttf ---> console

```
OTS parsing error: vhea: Failed to parse metrics in vhea
```

download [foo.ttf](http://78rgdb.com1.z0.glb.clouddn.com/FZJDJT.TTF)

**Comment by Jijun** [comment]
there's an error in your ttf file

**Comment by inbreaks** [comment]
such as?

**Comment by davelab6** [comment]
OTS will report the error
