### ISSUE TITLE
Exception when subsetting otf font

### ISSUE THREAD

**Issue by WickyNilliams** [googlei18n/sfntly#64]
I have been attempting to use sfnttool to subset Google's own Noto Sans font. For CJK languages, Noto is only offered in `otf` format (other languages are in `ttf`). 

If I subset standard Noto (ttf), it works fine:

```bash
sfnttool -s helo NotoSans-Regular.ttf NotoSans-Regular-subset.ttf
```

However, if I attempt the same with the CJK-JP version of Noto (otf), I get the following exception:

```bash
sfnttool -s helo NotoSansCJKjp-Regular.otf NotoSansCJKjp-Regular-subset.otf

Exception in thread "main" java.lang.NullPointerException
	at com.google.typography.font.tools.sfnttool.GlyphCoverage.getGlyph(Unknown Source)
	at com.google.typography.font.tools.sfnttool.GlyphCoverage.touchGlyph(Unknown Source)
	at com.google.typography.font.tools.sfnttool.GlyphCoverage.getGlyphCoverage(Unknown Source)
	at com.google.typography.font.tools.sfnttool.SfntTool.subsetFontFile(Unknown Source)
	at com.google.typography.font.tools.sfnttool.SfntTool.main(Unknown Source)
```

Is there something I am missing here, or does `sfnttool` simply not support otf? In my understanding converting opentype to truetype is a lossy conversion, so it not a suitable workaround here

**Comment by jtanx** [comment]
As far as I know, sfntly doesn't support subsetting otf/CFF style fonts

**Comment by WickyNilliams** [comment]
Thanks for the reply Jeremy. I was worried that might be the case, but there seems to be [a lot of code related to opentype](https://github.com/googlei18n/sfntly/tree/master/java/src/com/google/typography/font/sfntly/table/opentype) in the repo. 

Also [this article](http://googlecode.blogspot.co.uk/2011/11/build-great-font-tools-and-services.html) says it is supported. Emphasis mine:

> Starting today, both Java and C++ programmers can use sfntly to quickly and easily develop code to read, edit, and **subset OpenType and TrueType fonts**

So I would assume it is supported generally, but `sfnttool` does not support it?

**Comment by moyogo** [comment]
@WickyNilliams "OpenType" and "TrueType" don’t mean what you think. An OpenType font can be a TrueType font (OpenType/TTF) or a CFF font (OpenType/CFF). So that statement you quote is not complete but not false.

Try https://github.com/fonttools/fonttools. The pyftsubset tool can subset OpenType/TTF and OpenType/CFF.

**Comment by WickyNilliams** [comment]
Ah, yes, I remember reading something about this. I assume that, eventually, sfntly will have to support both TTF and CFF when Noto Sans is released on Google's font service?

I have already switched to `pyftsubset`. it works perfectly :)

**Comment by behdad** [comment]
Yes, use `pyftsubset`.
