### ISSUE TITLE
Support subsetting of CFF-based fonts

### ISSUE THREAD

**Issue by jfkthame** [googlei18n/sfntly#71]
To allow sfntly to be useful for a larger repertoire of fonts, obviously.

**Comment by behdad** [comment]
You mean the C++ code? Do you use it for printing?

We've been trying to kill sfntly as the Java code is mostly unused, in favor of fontTools subsetter (except for missing EOT support right now), and the C++ code is far from complete and definitely unmaintained. I've talked to Adrian Johnson to make a library out of cairo's font subsetting code for years, but no one was motivated enough to do it.  I'd really appreciate Mozilla pushing in that direction if you can use the resulting library. That's definitely much better tested and maintained than sfntly.

**Comment by jfkthame** [comment]
OK, that's interesting feedback. Yes, we have sfntly hooked up to SkiaPDF for printing purposes in certain circumstances - I'm not really sure of the exact details - and are conscious that it doesn't help for CFF-based fonts. But your comments re (lack of) maintenance etc are definitely worth some consideration. We'll no doubt talk about it some more...

**Comment by behdad** [comment]
> We'll no doubt talk about it some more...

Thanks. I'm open to looping in Adrian and Chrome people and working together on a replacement.

**Comment by khaledhosny** [comment]
I thought sfntly can subset CFF fonts and was just looking for using it in LibreOffice. Good that I found this early enough.

**Comment by behdad** [comment]
We have some plans for a unified C/C++ font subsetter.  I'll contact you separately.
